package it.polimi.ingsw.gc31.client_server;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

import it.polimi.ingsw.gc31.exceptions.NoFileCreatedException;
import it.polimi.ingsw.gc31.exceptions.NoTokenException;
import it.polimi.ingsw.gc31.utility.FileUtility;

public class Token {
    /**
     * Value used to determine a specific client in the server database
     */
    private int token;
    /**
     * Value used only for the very first connection between client and server. Is the first token value generated by the server
     * and when the client inserts the username a new token is generated (token) that will be used for the future connection
     * of this client
     */
    private int tempToken = 0;

    /**
     * Is the constructor of the Token. Tries to read the value saved in the file, if there is not any value in the file
     * it is set to -1
     */
    public Token() {
        try {
            this.token = Integer.parseInt(getTokenLine());
        } catch (NumberFormatException e) {
            e.printStackTrace();
            this.token = -1;
            // TODO
            // eliminare il file
        } catch (NoTokenException e) {
            this.token = -1;
        }
    }

    /**
     * This method reads all the lines in the file and return the string corresponding to the token red
     *
     * @return the line corresponding to the token
     * @throws NoTokenException if the file does not exist
     */
    public String getTokenLine() throws NoTokenException {
        Path file = FileUtility.getCodexTokenFilePath();
        List<String> lines = new ArrayList<>();
        if (doesTokenExists()) {
            try {
                lines = Files.readAllLines(file);
            } catch (IOException e) {
                e.printStackTrace();
            }
            // ui.showGenericClientResonse("TOKEN: " + lines.get(0));
            return lines.get(0);
        } else {
            throw new NoTokenException();
        }
    }

    /**
     * A method that checks if the file exists
     *
     * @return true if the file exists, false otherwise
     */
    public boolean doesTokenExists() {
        Path file = FileUtility.getCodexTokenFilePath();
        if (Files.exists(file)) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * A method that checks if the folder, where the token value should be stored, exist
     *
     * @return true if the folder exists, false otherwise
     */
    public boolean doesCodexFolderExists() {
        Path file = FileUtility.getCodexNaturalisPath();
        if (Files.exists(file)) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * This method overwrite the value of the token found in the file. If the folder does not exist it is created. If
     * the file already exists it is eliminated and then created. Lastly the value of the token is wrote
     *
     * @return the boolean value corresponding to the existence of the folder
     */
    public boolean rewriteTokenFile() {
        boolean alreadyExists = false;
        // se non esiste la cartella la crea
        if (!doesCodexFolderExists())
            try {
                FileUtility.createDirectory(null, FileUtility.folderName, true);
            } catch (NoFileCreatedException e) {
                e.printStackTrace();
            }
        Path filePath = FileUtility.getCodexTokenFilePath();
        // se il file esiste lo cancella
        if (Files.exists(filePath)) {
            try {
                Files.delete(filePath);
            } catch (IOException e) {
                e.printStackTrace();
            }
            alreadyExists = true;
        }
        // crea e scrive il file
        try (BufferedWriter writer = Files.newBufferedWriter(filePath, StandardOpenOption.CREATE,
                StandardOpenOption.APPEND)) {
            writer.write("" + token);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return alreadyExists;
    }

    /**
     * A method that returns the value of the tempToken
     *
     * @return the value of the tempToken
     */
    public int getTempToken() {
        return tempToken;
    }

    /**
     * A method that set the value of the tempToken to a value obtained as a parameter
     *
     * @param tempToken is the value to be set as the new tempToken
     */
    public void setTempToken(int tempToken) {
        this.tempToken = tempToken;
    }

    /**
     * A method that returns the value of the token
     *
     * @return the value of the token
     */
    public int getToken() {
        return token;
    }

    /**
     * A method that set the value of the tempToken to a value obtained as a parameter
     *
     * @param token is the value to be set as the new tempToken
     */
    public void setToken(int token) {
        this.token = token;
    }

    /**
     * The constructor of the Object Token that sets a specific value of the token attributes on creation
     *
     * @param token is the value to be set as the token
     */
    public Token(int token) {
        this.token = token;
    }
}
